set serveroutput on size 1000000

REM  +=======================================================================+
REM  |  FILENAME:  dml_upd_claims_attribute_hd.sql
REM  |
REM  |  DESCRIPTION: Create configuration script to update descriptions and disable
REM  |			 the TOTAL LOSS/STOLEN CLAIM flex table attributes
REM  |
REM  |  PREREQUISITE:
REM  |
REM  |
REM  |  HISTORY :
REM  |  Creation Date :	12/03/2019   dschilling
REM  +=======================================================================+

BEGIN
UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_ENABLED_IND ='N',
	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
AND FTA_TABLE_ATTRIBUTE IN ('CLAIM_006','CLAIM_007','CLAIM_008','CLAIM_009','CLAIM_013','CLAIM_014','ATA_5_ITM_3','ATA_5_ITM_4','ATA_5_ITM_5','ATA_5_ITM_6',
					   'ATA_5_ITM_7','ATA_5_ITM_8','ATA_5_ITM_9','ATA_5_ITM_10','ATA_5_ITM_11','ATA_5_ITM_12','ATA_5_ITM_13','ATA_5_ITM_14',
					   'ATA_5_ITM_15','ATA_5_ITM_16','ATA_5_ITM_17','ATA_5_ITM_18','ATA_5_ITM_19','ATA_5_ITM_20','ATA_5_ITM_21','ATA_5_ITM_22',
					   'ATA_5_ITM_23','ATA_5_ITM_24','ATA_5_ITM_25','ATA_5_ITM_26','ATA_5_ITM_27','ATA_5_ITM_28','ATA_5_ITM_29','ATA_5_ITM_30',
					   'ATA_5_ITM_31','ATA_5_ITM_32','ATA_5_ITM_33','ATA_5_ITM_34','ATA_5_ITM_35','ATA_5_ITM_36','ATA_5_ITM_37','ATA_5_ITM_38',
					   'ATA_5_ITM_39','ATA_5_ITM_40','ATA_5_ITM_41','ATA_5_ITM_42','ATA_5_ITM_43','ATA_5_ITM_44','ATA_5_ITM_45','ATA_5_ITM_46',
					   'ATA_5_ITM_47','ATA_5_ITM_48','ATA_5_ITM_49','ATA_5_ITM_50','ATA_5_ITM_51','ATA_5_ITM_52','ATA_5_ITM_53','ATA_5_ITM_54',
					   'ATA_5_ITM_55','ATA_5_ITM_56','ATA_5_ITM_57','ATA_5_ITM_58','ATA_5_ITM_59','ATA_5_ITM_60','ATA_5_ITM_61','ATA_5_ITM_62',
					   'ATA_5_ITM_63','ATA_5_ITM_64','ATA_5_ITM_65','ATA_5_ITM_66','ATA_5_ITM_67','ATA_5_ITM_68','ATA_5_ITM_69','ATA_5_ITM_70',
					   'ATA_5_ITM_71','ATA_5_ITM_72','ATA_5_ITM_73','ATA_5_ITM_74','ATA_5_ITM_75');

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A1-TYPE OF LOSS',
 	FTA_SORT = 1,
	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_001';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A2-INSURANCE COMPANY NAME (REQUIRED)',
 	FTA_SORT = 2,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_003';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A3-INSURANCE COMPANY PHONE # (REQUIRED)',
 	FTA_SORT = 3,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_004';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A4-CLAIM # (REQUIRED)',
 	FTA_SORT = 4,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_005';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A5-INS FAX #',
 	FTA_SORT = 3,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_010';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A6-LETTER OF GUARANTEE AMOUNT',
 	FTA_SORT = 6,
	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_011';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A7-DEDUCTIBLE AMOUNT',
 	FTA_SORT = 7,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_012';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A8-NADA AMOUNT',
 	FTA_SORT = 8,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_015';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'A9-DATE OF LOSS',
 	FTA_SORT = 9,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_016';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B1-ADJUSTOR NAME',
 	FTA_SORT = 10,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_017';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B2-ADJUSTOR PHONE EXT',
 	FTA_SORT = 11,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_018';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B3-MILEAGE',
 	FTA_SORT = 12,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_019';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B4-POLICE DEPARTMENT',
 	FTA_SORT = 13,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_020';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B5-POLICE PHONE #',
 	FTA_SORT = 14,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_021';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B6-POLICE REPORT #',
 	FTA_SORT = 15,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'CLAIM_022';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B7-COMMENT 1',
 	FTA_SORT = 16,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'ATA_5_ITM_1';

UPDATE FLEX_TABLE_ATTRIBUTES
 SET FTA_DESC = 'B8-COMMENT 2',
 	FTA_SORT = 17,
 	LAST_UPDATED_BY = 'TASK0747545',
	LAST_UPDATE_DATE = SYSDATE
WHERE FTA_FTB_TABLE = 'TAB_ATA_5'
  AND FTA_TABLE_ATTRIBUTE = 'ATA_5_ITM_2';

END;

 /
SHOW ERR
set serveroutput off
PROMPT Please COMMIT after making sure NO errors generated
